server:
  port: 8081
spring:
  application:
    name: catalogue-service
  jpa:
    show-sql: true
  sleuth:
    sampler:
      probability: 1
management:
  endpoints:
    web:
      exposure:
        include: "*"
